* SPICE FF
* fast-fast corner (fastest operating corner)

.inc ./tran_models/models_ff/NMOS_VTG.inc
.inc ./tran_models/models_ff/PMOS_VTG.inc

.inc ./tran_models/models_ff/NMOS_VTL.inc
.inc ./tran_models/models_ff/PMOS_VTL.inc

.inc ./tran_models/models_ff/NMOS_VTH.inc
.inc ./tran_models/models_ff/PMOS_VTH.inc

.inc ./tran_models/models_ff/NMOS_THKOX.inc
.inc ./tran_models/models_ff/PMOS_THKOX.inc
