* SPICE NOM
* nominal operating corner (average operating corner)

.inc ./tran_models/models_nom/NMOS_VTG.inc
.inc ./tran_models/models_nom/PMOS_VTG.inc

.inc ./tran_models/models_nom/NMOS_VTL.inc
.inc ./tran_models/models_nom/PMOS_VTL.inc

.inc ./tran_models/models_nom/NMOS_VTH.inc
.inc ./tran_models/models_nom/PMOS_VTH.inc

.inc ./tran_models/models_nom/NMOS_THKOX.inc
.inc ./tran_models/models_nom/PMOS_THKOX.inc
