* SPICE SS
* slow-slow corner (slowest operating corner)

.inc ./tran_models/models_ss/NMOS_VTG.inc
.inc ./tran_models/models_ss/PMOS_VTG.inc

.inc ./tran_models/models_ss/NMOS_VTL.inc
.inc ./tran_models/models_ss/PMOS_VTL.inc

.inc ./tran_models/models_ss/NMOS_VTH.inc
.inc ./tran_models/models_ss/PMOS_VTH.inc

.inc ./tran_models/models_ss/NMOS_THKOX.inc
.inc ./tran_models/models_ss/PMOS_THKOX.inc
